# Generated by Django 2.2.6 on 2019-11-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perioddate',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='perioddate',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
