# Generated by Django 2.2.6 on 2019-10-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20191024_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_login',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_login',
            field=models.BooleanField(default=False),
        ),
    ]
